import './globals.css';
import { Young_Serif } from 'next/font/google';

const youngSerif = Young_Serif({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-young-serif',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={youngSerif.className}>{children}</body>
    </html>
  );
}
